name: Add issues with the `status/triage` label to the project

on:
  issues:
    types:
      - labeled
permissions:
  repository-projects: write
  issues: read
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: echo ${{ github.event.issue.number }}; echo ${{github.token}}
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Zaperex/projects/2
          github-token: ${{ github.token }}
          labeled: status/triage
