name: Add issues with the `status/triage` label to the project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Zaperex/projects/2
          github-token: ${{ secrets.PRIVATE_TOKEN }}
          labeled: status/triage
