name: Add issues with the `status/triage` label to the project

on:
  issues:
    types:
      - labeled
permissions:
  repository-projects: write
  issues: read
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.event.issue.payload }}";
          echo "${{github.token}}"
          echo "${{secrets.GITHUB_TOKEN}}"
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Zaperex/projects/2
          github-token: ${{ github.token }}
          labeled: status/triage
